### ISSUE TITLE
Documentation for ExtraInfoDescriptor.ip_transports calls it ip_versions

### ISSUE THREAD

**Issue by Em4E** [torproject/stem#120]
https://stem.torproject.org/api/descriptor/extrainfo_descriptor.html

> * **ip_versions** (*dict*) -- mapping of ip protocols to a rounded count for the number of users
> * **ip_versions** -- mapping of ip transports to a count for the number of users

The second **ip_versions** should be **ip_transports**.

**Comment by aadarsh-nagrath** [comment]
Yeah....ip_versions" is repeated twice

**Comment by Em4E** [comment]
The online documentation still has the error ([e.g.](https://web.archive.org/web/20240107002344/https://stem.torproject.org/api/descriptor/extrainfo_descriptor.html)), but otherwise it looks like this was fixed in #148.
