### ISSUE TITLE
No release to fix Python 3.11 compatibility error in nyx

### ISSUE THREAD

**Issue by fungs** [torproject/stem#130]
In [nyx](https://github.com/torproject/nyx/) we still get an error: 

```
~ # nyx
Traceback (most recent call last):
  File "/usr/bin/nyx", line 33, in <module>
    sys.exit(load_entry_point('nyx==2.1.0', 'console_scripts', 'nyx')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/nyx/__init__.py", line 176, in main
    nyx.starter.main()
  File "/usr/lib/python3.11/site-packages/stem/util/conf.py", line 288, in wrapped
    if 'config' in inspect.getargspec(func).args:
                   ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
```

Fixed in this commit, but not released:

https://github.com/torproject/stem/commit/b8063b3b23af95e02b27848f6ab5c82edd644609

**Comment by atagar** [comment]
Hi Johannes. As discussed on a few other issues (#126, #127, #118) you'll need to contact 'gk at torproject dot org' if you'd care for this to change.

**Comment by bober757** [comment]
stem/control.py line 477:
`      arg_names = inspect.getfullargspec(func).args[1:]  # drop 'self'`

stem/util/conf.py line 288:
`      if 'config' in inspect.getfullargspec(func).args:`

**Comment by fungs** [comment]
Hey, thanks for your feedback @bober757! At first sight, this repo looks like the correct place to report such a severe issue. It also seems that the changes needed only affect this repo and seem to be already implemented. Maybe you could please explain why I should contact someone else for this? Is this a deficiency of how the tor repos and development process is organized?

From my user perspective: I tried it, it didn't work, I reported the issue, I'll maybe use it in the future if it gets fixed, otherwise it will remain useless.

**Comment by atagar** [comment]
> Maybe you could please explain why I should contact someone else for this?

Hi fungs. I'm the author of Stem and Nyx. I developed them for a decade but left Tor a couple years ago. Afterward Georg (a Tor employee) opted to be Stem's maintainer but he does not monitor GitHub. Ergo my suggestion to email him.

**Comment by fungs** [comment]
Thanks @atagar @jefferyto for following up on this. I will dig out my project and give it a try, again.
