### ISSUE TITLE
failed to detect python in AppImage

### ISSUE THREAD

**Issue by Brensom** [torproject/stem#139]
Hello.
I am using Python in AppImage https://python-appimage.readthedocs.io/en/latest/
And when installing "stem" I get the error:

> • Installing stem (1.8.1): Failed
>   RuntimeError
> 
>   failed to detect python3.10.12-cp310-cp310-manylinux_2_28_x86_3.10.12-64|python3.10.12-cp310-cp310-manylinux_2_28_x86_3.10.12|python3.10.12-cp310-cp310-manylinux_2_28_x86_3.10-64|python3.10.12-cp310-cp310-manylinux_2_28_x86_3.10|python3.10.12-cp310-cp310-manylinux_2_28_x86_3-64|python3.10.12-cp310-cp310-manylinux_2_28_x86_3|python3.10.12-cp310-cp310-manylinux_2_28_x86_-64|python3.10.12-cp310-cp310-manylinux_2_28_x86_|PYTHON3.10.12-CP310-CP310-MANYLINUX_2_28_X86_3.10.12-64|PYTHON3.10.12-CP310-CP310-MANYLINUX_2_28_X86_3.10.12|PYTHON3.10.12-CP310-CP310-MANYLINUX_2_28_X86_3.10-64|PYTHON3.10.12-CP310-CP310-MANYLINUX_2_28_X86_3.10|PYTHON3.10.12-CP310-CP310-MANYLINUX_2_28_X86_3-64|PYTHON3.10.12-CP310-CP310-MANYLINUX_2_28_X86_3|PYTHON3.10.12-CP310-CP310-MANYLINUX_2_28_X86_-64|PYTHON3.10.12-CP310-CP310-MANYLINUX_2_28_X86_|cpython3.10.12-64|cpython3.10.12|cpython3.10-64|cpython3.10|cpython3-64|cpython3|cpython-64|cpython|CPython3.10.12-64|CPython3.10.12|CPython3.10-64|CPython3.10|CPython3-64|CPython3|CPython-64|CPython|CPYTHON3.10.12-64|CPYTHON3.10.12|CPYTHON3.10-64|CPYTHON3.10|CPYTHON3-64|CPYTHON3|CPYTHON-64|CPYTHON|python3.10.12-64|python3.10.12|python3.10-64|python3.10|python3-64|python3|python-64|python|PYTHON3.10.12-64|PYTHON3.10.12|PYTHON3.10-64|PYTHON3.10|PYTHON3-64|PYTHON3|PYTHON-64|PYTHON in /tmp/.mount_pythonUPytrv/opt/python3.10
> 
>   at /tmp/python/lib/python3.10/site-packages/virtualenv/discovery/py_info.py:460 in discover_exe
>       456│             self._cache_exe_discovery[key] = info
>       457│             logging.debug("no exact match found, chosen most similar of %s within base folders %s", info, folders)
>       458│             return info
>       459│         msg = "failed to detect {} in {}".format("|".join(possible_names), os.pathsep.join(possible_folders))
>     → 460│         raise RuntimeError(msg)
>       461│ 
>       462│     def _check_exe(self, app_data, folder, name, exact, discovered, env):  # noqa: PLR0913
>       463│         exe_path = os.path.join(folder, name)
>       464│         if not os.path.exists(exe_path):

**Comment by atagar** [comment]
Hi Brensom. I'm unfamiliar with AppImage and there's nothing within this stacktrace that looks to be related to Stem. If there's an issue with Stem itself then please feel free to reopen but I don't see anything that's actionable on our end.
