### ISSUE TITLE
Commits from fork have been pulled in along with PR

### ISSUE THREAD

**Issue by PascalinDe** [torproject/stem#144]
Hey, not sure how this happened but merging https://github.com/torproject/stem/pull/135 yesterday seems to have pulled in some commits on our fork as well:

* https://github.com/torproject/stem/commit/ce2a14814137f6d60a7f2305ccf7aa6d04bc5579
* https://github.com/torproject/stem/commit/668abcf66975128a612019bb977b37dd268e116a
* https://github.com/torproject/stem/commit/114f140d2c5baa4bb484539e0ae11bc957c5663a

oddly enough two of these are commits that I created after updating the PR.

The commit history of that branch does not contain the commits either:

![Screenshot 2023-10-12 at 10-00-34 Commits · c4dt_stem](https://github.com/torproject/stem/assets/15922677/97b96a2e-9544-4158-a6cc-e3e24b486dd8)

**Comment by PascalinDe** [comment]
added PR #145 to remedy this

**Comment by atagar** [comment]
Oops, thanks Carine. My bad. When I merged your recent work all the commits looked decent to me so I pulled everything in. Merged the revert.

**Comment by PascalinDe** [comment]
OK, thanks

I'll probably open one or the other PR with them as well, it's just that they haven't all been properly tested yet
