### ISSUE TITLE
Update dirauth details

### ISSUE THREAD

**Issue by juga0** [torproject/stem#150]
Hi @atagar, 

as you can see, we've cherry-picked some commits from master to create a new stem point release 1.8.3. We also added a few commits that aren't in master. One of them, in concrete, maybe you would like to add it to master, otherwise doctor doesn't work. The commit is https://github.com/torproject/stem/commit/1c17f03cd5eca811f912cf650ce0c14cbcc21fe2.

Thanks!

**Comment by atagar** [comment]
Cherry-picked it onto the master branch.
