### ISSUE TITLE
setup.py needs cleanup

### ISSUE THREAD

**Issue by atagar** [torproject/stem#43]
**Migrated from ticket [31234](https://trac.torproject.org/projects/tor/ticket/31234).**

1. We should avoid importing our own modules as this prevents us from being installed from other directories.
2. Optionally use setuptools so bdist_wheel can be available.

**Comment by msramalho** [comment]
Hey @atagar, I will be trying to fix this.

I have found a [very interesting page](https://packaging.python.org/guides/single-sourcing-package-version/) that gives several options to solve this. Can you please take a look and check which would make more sense?

In the meantime, I have migrate distutils to setuptools

**Comment by msramalho** [comment]
By the way, the [original ticket] mentioned:
*. All the large strings should be in separate files.
Should this also be fixed, if what's the criteria to use when telling which strings to isolate to a file?

**Comment by atagar** [comment]
Thanks Miguel! [Pushed along with some test fixes](https://gitweb.torproject.org/stem.git/commit/?id=2c043f4).

As for getting the package version thanks for pointing that out! We actually previously did the first option, so we could probably simply revert [this](https://gitweb.torproject.org/stem.git/commit/?id=3b2a31b) to do that.

**Comment by msramalho** [comment]
Hey @atagar, thanks for the tips, I have adapted the previous code and submitted another PR.

**Comment by atagar** [comment]
Thanks Miguel! [Merged](https://gitweb.torproject.org/stem.git/commit/?id=ec26b63).
