### ISSUE TITLE
Allow run_test.py to disable particular unit tests in a set of tests

### ISSUE THREAD

**Issue by teor2345** [torproject/stem#53]
Some of stem's tests hang in Tor's Travis CI.

So we'd like to be able to say something like:
`run_tests.py --test process --exclude-test process.test_take_ownership_via_controller`

**Comment by atagar** [comment]
Thanks teor! This is a great idea. I've made --exclude-test work in a similar way to --test, so it can either skip test modules **or** individual tests. For a couple examples please see...

https://gitweb.torproject.org/stem.git/commit/?id=886ec10

Feel free to reopen if you'd like any adjustments.

**Comment by teor2345** [comment]
Thanks for this change!

We don't need it right now, because all the stem tests are passing. (Thanks for helping us with those fixes.) But it will be useful in future, when we need to diagnose CI issues.
