### ISSUE TITLE
Outdated button link

### ISSUE THREAD

**Issue by woswos** [torproject/stem#64]
Hi,

The development button on the navigation bar of this page (https://stem.torproject.org/index.html) links to the old trac page, fyi.

<img width="720" alt="Screen Shot 2020-06-03 at 11 17 25 PM" src="https://user-images.githubusercontent.com/10498874/83684891-6d238580-a5f0-11ea-9e56-5ddc266fe496.png">

**Comment by atagar** [comment]
Thanks Barkin, great catch! I'll be busy with a feature branch for a while but I'll fix this once that's done.

**Comment by arthtyagi** [comment]
Fixed this issue with https://github.com/torproject/stem/pull/65

**Comment by woswos** [comment]
closing this issue since it is fixed now
