### ISSUE TITLE
Tor has a new ORPort listeners by default

### ISSUE THREAD

**Issue by dgoulet-tor** [torproject/stem#70]
Tor git master just merged its support to automatically have an IPv6 `ORPort` by default. Which means that `ORPort 9001` for instance will both open a listener on `0.0.0.0` and `[::]` leading in this error with `test_get_listeners` and `test_get_ports`:

https://travis-ci.org/github/torproject/tor/jobs/710747893#L3773

```
Second list contains 1 additional elements.
First extra element 1:
('::', 1113)

- [('0.0.0.0', 1113)]
+ [('0.0.0.0', 1113), ('::', 1113)]
```

**Comment by atagar** [comment]
Thanks David! Fixed.

https://gitweb.torproject.org/stem.git/commit/?id=435b980
