### ISSUE TITLE
Not receiving any Stream Events

### ISSUE THREAD

**Issue by aaronst** [torproject/stem#79]
I tried using the code from [exits_used.py](https://stem.torproject.org/tutorials/examples/exit_used.html), but I'm not getting any output. I removed any conditions, and it appears I don't get any Stream events at all. My `torrc` file only specifies the control port, and I'm using the same `curl` command provided with the script. I'm running Python 3.8.6 and `stem==1.8.0`. Any help would be appreciated, thanks!

**Comment by atagar** [comment]
Hi Aaron. Are you getting the same output from curl as the example (ie. is the curl request completing successfully)?

**Comment by aaronst** [comment]
Good timing, I finally figured it out. My callback function was causing an error, which has happening silently. So events were coming in, I just wasn't seeing them.
