### ISSUE TITLE
Do not return generator when DocumentHandler is DOCUMENT

### ISSUE THREAD

**Issue by jbrown299** [torproject/stem#82]
```python
    with open('cached-microdesc-consensus', 'rb') as consensus_file:
        network_status = parse_file(consensus_file,
                                    'network-status-microdesc-consensus-3 1.0',
                                    document_handler=DocumentHandler.DOCUMENT,
                                    validate=True)
```

So here is `parse_file` always return generator. In my opinion will be better if we parse as single document return object but not generator.

Or you mean it is possible to load several documents from one file?

**Comment by atagar** [comment]
Hi James. You're right that this is a common gotcha, please use `next`...

```
network_status = next(parse_file(...))
```

Some files contain a single descriptor, whereas others have multiple. Varying our return type based on the context would make this function even more confusing to use.
