### ISSUE TITLE
Use enum for `flags` field in `RouterStatusEntry`

### ISSUE THREAD

**Issue by jbrown299** [torproject/stem#83]
For now it's list of strings:
```python
flags = ['Fast', 'Guard', 'HSDir', 'Running', 'Stable', 'V2Dir', 'Valid']
```

Better to use enum.

**Comment by atagar** [comment]
Hi James. RouterStatusEntry already uses our Flag enum.

https://stem.torproject.org/api/descriptor/router_status_entry.html#stem.descriptor.router_status_entry.RouterStatusEntry
https://stem.torproject.org/api/control.html#stem.Flag
