### ISSUE TITLE
Use enum for `known_flags` field in `NetworkStatusDocument`

### ISSUE THREAD

**Issue by jbrown299** [torproject/stem#84]
For now it's list of strings:
```
['Authority', 'BadExit', 'Exit', 'Fast', 'Guard', 'HSDir', 'NoEdConsensus', 'Running', 'Stable', 'StaleDesc', 'V2Dir', 'Valid']
```

**Comment by atagar** [comment]
Hi James. NetworkStatusDocument already uses our Flag enum.

https://stem.torproject.org/api/descriptor/networkstatus.html#stem.descriptor.networkstatus.NetworkStatusDocumentV3
https://stem.torproject.org/api/control.html#stem.Flag
