### ISSUE TITLE
Example exit_used.py not working

### ISSUE THREAD

**Issue by Jiw0cha** [torproject/stem#94]
Hello.

I run https://github.com/torproject/stem/blob/63a476056017dda5ede35efc4e4f7acfcc1d7d1a/docs/_static/example/exit_used.py
and stream_event not сalled

I use:
stem==1.8.0
Tor version 0.4.2.7.

**Comment by atagar** [comment]
Hi Jim. I can't remotely troubleshoot that. Maybe you didn't visit anything in your tor browser or you attached to a different tor instance?

**Comment by Jiw0cha** [comment]
> Maybe you didn't visit anything in your tor browser or you attached to a different tor instance?

I don't use tor browser. I run tor as service. And after run script exit_used.py, i see in log tor:

Apr 12 18:57:08 localhost.localdomain Tor[17870]: New control connection opened from 127.0.0.1.

It connects, but nothing does.
Is there any way to debug?

**Comment by atagar** [comment]
> I don't use tor browser. I run tor as service.

I think there might be a misunderstanding about what that script does. When you send client traffic through tor (ie, use the tor network) the exit_used.py tells you the relay your traffic exited from. If you don't send anything through tor the script will rightfully not present anything.

**Comment by Jiw0cha** [comment]
> > I don't use tor browser. I run tor as service.
> 
> I think there might be a misunderstanding about what that script does. When you send client traffic through tor (ie, use the tor network) the exit_used.py tells you the relay your traffic exited from. If you don't send anything through tor the script will rightfully not present anything.

Thanks. Worked!
